### ISSUE TITLE
IE 8 with iframe

### ISSUE THREAD

**Issue by ParadimeWeb** [asual/jquery-address#1] opened 2010-02-23 17:08 UTC
First off, the plugin is working great with Firefox and IE 7.

I am experiencing a bug with IE 8. I have a page that uses $.address. Inside that page I have an iframe with a page that uses $.address as well. It seems like the $.address.change inside the page in the iframe overrides the one in the parent window..

Thanks,

**Comment by asual** [comment] 2010-02-23 22:56
I just pushed a fix that improves the overall support for the onhashchange event. Can you please check if it solves your problem.

**Comment by ParadimeWeb** [comment] 2010-02-23 23:27
It seems to work now but only if the page in the src of the iframe is loaded. If I load the src of the iframe using javascript, I get a function or method not supported. As if address lib was not loaded.

At least I can make it work one way now.

Thanks,

**Comment by asual** [comment] 2010-03-01 21:18
Can you please test the latest version once again. It works well against my test case but it probably depends.

**Comment by asual** [comment] 2010-03-31 22:14
Assuming that the issue is resolved.

**Closed as completed by asual** 2010-03-31 22:14 UTC

**Comment by danielhai** [comment] 2010-09-06 20:20
This issue is still occuring for me using version 1.2.2, browser Chrome: 6+

**Comment by asual** [comment] 2010-09-08 20:14
The issue is specific to IE and it has been fixed.
