### ISSUE TITLE
d not defined in jQuery 1.4.2 with samples uploaded to remote server

### ISSUE THREAD

**Issue by eli007s** [asual/jquery-address#13] opened 2010-07-14 23:19 UTC
I uploaded the tabs folder directly to my host and ran the index.html. Firebug throws me an error stating that function d is not defined, if Firebug is disabled then it runs as intended across all browsers. Just having this issue with Firefox and Firebug with the Script feature turned on.

I ran into this before when the jQuery file wasn't either loaded or needed to be upgraded. But seeing how the test samples are run as-is I'm not sure what could be causing the problem.

http://www.helixagent.com/list/tabs/

**Comment by asual** [comment] 2010-07-15 11:02
I can't reproduce it here. Try on another computer. If the problem exists there then please report the exact versions of both Firefox and Firebug.

**Comment by eli007s** [comment] 2010-07-15 11:27
Yes, you are correct. For some reason my browser cache wasn't clearing properly. Its all working now.

One question tho, How are external pages suppose to behave once loaded into the "tab"?

I have another jQuery plugin running on an external form perfectly. But once loaded into my page tab it breaks the external page completely. I have tried changing to the path pointers or adding the script/plug-ins into the main page to see if that would fix it but still not working.

this is a test scenario to public access: http://www.helixagent.com/list/tabs/test/index.php

the page being loaded is at: http://www.helixagent.com/list/includes/add.listings.inc.php

as you can see the page works independently, but not when its being retrieved by the jquery Address plugin

**Comment by asual** [comment] 2010-07-15 11:35
I'm going to close this issue since it's invalid. 

The provided sample loads external pages using the functionality provided by the tabs widget. Remove jQuery Address to ensure that it works as expected with the plain tabs. Please, use the contact form on asual.com for further discussion.

**Closed as completed** 2010-07-15 18:35 UTC

**Comment by feklee** [comment] 2010-09-21 14:38
I have the same problem.

How to Reproduce:
1. Start Firefox
2. Start Firebug
3. Go to URL:

http://localhost/tmp-work/jquery_history_test/asual-jquery-address-8e39526/samples/api/

or

http://localhost/tmp-work/jquery_history_test/jquery.address-1.2.2/samples/api/

Software:

jQuery Address 1.2.2 or current
Firefox 3.6.10 (caching settings: "Clear history when Firefox closes")
Firebug
WinXP/32 SP3

**Comment by asual** [comment] 2010-09-21 14:53
What's the exact version of Firebug? Do you get the error if you use the uncompressed file? Can you reproduce it on another computer? Do you see the issue in built-in Firefox Error Console? What's the encoding of the files served by your server? Do you experience the problem with samples[1] hosted at asual.com?
1. http://www.asual.com/jquery/address/samples/

**Comment by feklee** [comment] 2010-09-21 15:34
> What's the exact version of Firebug? 

1.5.4

> Do you get the error if you use the uncompressed file?

Yes.

> Can you reproduce it on another computer?

Tried it on Ubuntu 8.04, with the same versions of Firefox and Firebug,
and the same Firefox cache settings. Could _not_ reproduce it on that
system.

> Do you see the issue in built-in Firefox Error Console?

Execution stops in the script tab, with the aforementionned error
message.

It is enabled: "Break On All Errors"

> What's the encoding of the files served by your server?

UTF-8

> Do you experience the problem with samples[1] hosted at asual.com?

Yes.

**Comment by feklee** [comment] 2010-09-22 15:32
Do you need any further info? I'm interested in seeing this issue solved.

**Comment by asual** [comment] 2010-09-22 17:05
I need to find some time to fire up an XP virtual machine although I think I tried it in the past without being able to reproduce it.

Can you please tell me the exact line or statement in the source version of the script that causes the issue?

**Comment by feklee** [comment] 2010-09-22 17:10
At the moment, unfortunately, I cannot reproduce the problem either. Strange. Perhaps some timing issue.

**Comment by asual** [comment] 2010-09-25 08:09
Please, let me know which is the problematic line in the uncompressed file if you succeed reproducing the problem again.
